export { JiraClient } from './JiraClient';
export { JiraApiError } from './errors/JiraApiError';
export type { JiraClientOptions, RequestEvent, JiraClientEvents } from './JiraClient';
export { Security } from './security/Security';
export { IssueResource } from './resources/IssueResource';
export { ProjectResource } from './resources/ProjectResource';
export { BoardResource } from './resources/BoardResource';
export { SprintResource } from './resources/SprintResource';

// Domain types
export type { JiraIssue, JiraIssueFields, JiraTimeTracking, JiraSubtask, JiraResolution, IssueParams } from './domain/Issue';
export type { JiraSearchResponse, SearchParams } from './domain/IssueSearch';
export type { JiraProject, JiraProjectRef, JiraProjectStatus, JiraProjectRole, JiraProjectRoleActor, ProjectsParams } from './domain/Project';
export type { JiraUser, UserSearchParams } from './domain/User';
export type { JiraComment, JiraCommentResponse, JiraCommentVisibility, CommentsParams } from './domain/Comment';
export type { JiraWorklog, JiraWorklogResponse, WorklogsParams } from './domain/Worklog';
export type { JiraChangelogEntry, JiraChangelogItem, JiraChangelogResponse, ChangelogParams } from './domain/Changelog';
export type { JiraTransition, JiraTransitionField, TransitionsParams } from './domain/Transition';
export type { JiraAttachment } from './domain/Attachment';
export type { JiraIssueLink, JiraIssueLinkType, JiraIssueRef } from './domain/IssueLink';
export type { JiraRemoteLink, JiraRemoteLinkObject } from './domain/RemoteLink';
export type { JiraVotes } from './domain/Vote';
export type { JiraWatchers } from './domain/Watcher';
export type { JiraIssueType } from './domain/IssueType';
export type { JiraPriority } from './domain/Priority';
export type { JiraStatus, JiraStatusCategory } from './domain/Status';
export type { JiraComponent } from './domain/Component';
export type { JiraVersion, JiraVersionIssueCounts, JiraVersionUnresolvedIssueCount } from './domain/Version';
export type { JiraField } from './domain/Field';
export type { JiraFilter, JiraFilterPermission } from './domain/Filter';
export type { JiraBoard, JiraBoardFilter, JiraBoardProject, BoardsParams, BoardIssuesParams } from './domain/Board';
export type { JiraSprint, SprintsParams } from './domain/Sprint';
export type { PaginationParams, PagedResponse } from './domain/Pagination';
